# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-20 03:03
from __future__ import unicode_literals

import Base.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(max_length=32, verbose_name='单板类型')),
                ('board_present', models.CharField(max_length=32, verbose_name='在位状态')),
                ('board_register', models.CharField(max_length=32, verbose_name='注册状态')),
                ('board_where', models.CharField(max_length=32, verbose_name='所在设备')),
                ('board_slot', models.CharField(max_length=4, verbose_name='所在槽位')),
            ],
            options={
                'verbose_name': '单板信息',
                'verbose_name_plural': '单板信息表',
            },
            bases=(models.Model, Base.BaseModel.BaseModel),
        ),
    ]
