# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_ip', models.CharField(max_length=128)),
                ('product_type', models.CharField(max_length=64)),
                ('passwd', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('dev_linux_ip', models.CharField(max_length=128)),
                ('linux_passwd', models.CharField(max_length=32)),
                ('linux_name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('update_time', models.CharField(max_length=32)),
                ('status', models.CharField(default='fail', max_length=16)),
            ],
        ),
    ]
