# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-20 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinfo',
            options={'verbose_name': '设备信息', 'verbose_name_plural': '设备信息表'},
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='dev_ip',
            field=models.CharField(max_length=128, verbose_name='设备IP'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='dev_linux_ip',
            field=models.CharField(max_length=128, verbose_name='linux主机'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='linux_name',
            field=models.CharField(max_length=32, verbose_name='linux帐号'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='linux_passwd',
            field=models.CharField(max_length=32, verbose_name='linux密码'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='location',
            field=models.CharField(max_length=128, verbose_name='设备位置'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='name',
            field=models.CharField(default='szhw', max_length=32, verbose_name='设备帐号'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='passwd',
            field=models.CharField(default='Changeme_123', max_length=32, verbose_name='设备密码'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='product_type',
            field=models.CharField(max_length=64, verbose_name='产品形态'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='status',
            field=models.CharField(default='fail', max_length=16, verbose_name='设备连接状态'),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='update_time',
            field=models.CharField(max_length=32, verbose_name='设备信息更新时间'),
        ),
    ]
